### ISSUE TITLE
'dynamic module not initialized properly' error reported when import triton in python 2.7.13 installed via brew

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#577]
Hi ,recently I install new version of python2 with 'brew install python' on macos 10.12.   Brew installs python 2.7.13 successfully. Then I want to use triton with the new version of python. However, after compiling and installing successfully, when I import triton, the following error is reported:
```
Python 2.7.13 (default, Apr  4 2017, 08:47:57) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import triton
Traceback (most recent call last):
  File "/usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 539, in <module>
    main()
  File "/usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 521, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 266, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 241, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/local/bin/../Cellar/python/2.7.13/bin/../Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 231, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sysconfig.py", line 520, in get_config_var
    return get_config_vars().get(name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sysconfig.py", line 453, in get_config_vars
    import re
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 108, in <module>
    import _locale
SystemError: dynamic module not initialized properly
```
How to solve this error? Thanks very much

**Comment by JonathanSalwan** [comment]
What about importing others libs like capstone and stuff like that?

**Comment by vancaho** [comment]
I tried to  find whether some libraries are missing. Here are the results:
```
➜  build git:(master) pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
blessings (1.6)
capstone (3.0.4)
docopt (0.6.2)
pbr (3.1.1)
pip (9.0.1)
protobuf (3.3.0)
pyqt5-installer (5.7.0)
setuptools (32.1.0)
six (1.10.0)
stevedore (1.24.0)
virtualenv (15.1.0)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.2)
wget (3.2)
wheel (0.29.0)
z3-solver (4.5.1.0.post2)
```

Here are the results returned by looking whether the dependency libs are missing:
```
➜  build git:(master) otool -L /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/triton.so
/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/triton.so:
	@rpath/libtriton.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
	/usr/local/opt/z3/lib/libz3.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/capstone/lib/libcapstone.3.dylib (compatibility version 3.0.0, current version 3.0.4)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

Here are the logs displayed when configuring the project:
```
➜  build git:(master) cmake ..
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/local/bin/python2.7 (found suitable version "2.7.13", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found suitable version "2.7.10", minimum required is "2.7") 
-- Found Z3 
-- Found CAPSTONE 
-- Boost version: 1.64.0
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/fengchao/Codes/triton3/Triton/build
```

**Comment by JonathanSalwan** [comment]
Did you installed everything with `brew`? Btw, i'm not really comfortable with OSX but maybe you can see how we install and test it on [travis](https://github.com/JonathanSalwan/Triton/blob/master/.travis.yml)? (grep `"$TRAVIS_OS_NAME" == "osx"`).

**Comment by JonathanSalwan** [comment]
Can I close this or not?

**Comment by mrexodia** [comment]
I was having this issue too and it happens if you are not specifying (the correct) `PYTHON_LIBRARY` (and/or `PYTHON_INCLUDE_DIR`). [This comment](https://github.com/JonathanSalwan/Triton/issues/475#issuecomment-280060362) helped me a lot. To fix, find out where `python` is:

```
$ which python
/usr/local/bin/python
$ ls -l /usr/local/bin/python
lrwxr-xr-x  1 duncan  admin  38 Aug  8 01:08 /usr/local/bin/python -> ../Cellar/python@2/2.7.15_1/bin/python
```

In my case this means I have to use the following to build triton:

```
$ mkdir build && cd build
$ cmake .. -DPYTHON_LIBRARY=/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/Current/lib/libpython2.7.dylib -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/Current/include/python2.7
$ make -j
```

Then to test:

```
$ cd build/src/libtriton
$ python
>>> import triton
```

This should import triton as normal (try `triton.VERSION.BUILD` for example).
