### ISSUE TITLE
Fedora 32 (Python 3.8) setup.py error:  NameError: name 'execfile' is not defined

### ISSUE THREAD

**Issue by XVilka** [JonathanSalwan/Triton#893]
```
[i] ℤ pip install -U --user triton                                                                                                                                                                                                 18:03:16 
Collecting triton
  Downloading https://files.pythonhosted.org/packages/0c/83/06d92419894515d4b3de0d6b4d25c4a62b476bcc640a7b2701ef0bba7c52/triton-3.4.1.tar.gz
Collecting trytond<3.5,>=3.4
  Downloading https://files.pythonhosted.org/packages/6b/fa/8d71f7a8d017521d5516db2f4b5fc8ffae2a4a4017d0d5329b9c5b09b5fa/trytond-3.4.18.tar.gz (503kB)
     |████████████████████████████████| 512kB 385kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ebgozff7/trytond/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ebgozff7/trytond/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ebgozff7/trytond/pip-egg-info
         cwd: /tmp/pip-install-ebgozff7/trytond/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ebgozff7/trytond/setup.py", line 9, in <module>
        execfile(os.path.join('trytond', 'version.py'))
    NameError: name 'execfile' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by JonathanSalwan** [comment]
mmmmh,

I'm not sure [triton-3.4.1.tar.gz](https://pypi.org/project/triton/) is the same project as our. Actually, I'm not sure there is our Triton project on [pypi](https://pypi.org/search/?q=triton).

**Comment by XVilka** [comment]
Oh, lol. Upgraded the system and forgot how I installed Triton. Sorry for the noise.
